In [ ]:
import os
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/


In [ ]:
import pandas as pd
import numpy as np

In [ ]:
dataset = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Iris.csv')

In [ ]:
x = dataset.iloc[:,1:5].values
y = dataset.iloc[:,5].values

In [ ]:
from sklearn.preprocessing import LabelEncoder
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test =train_test_split(x,y,test_size=0.3)

In [ ]:
from sklearn.linear_model import LogisticRegression
logmodel = LogisticRegression()
logmodel.fit(x_train,y_train)

/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [ ]:
y_pred = logmodel.predict(x_test)
y_pred

array([2, 0, 0, 0, 2, 2, 0, 1, 0, 0, 1, 2, 1, 2, 2, 1, 0, 1, 0, 0, 1, 1,
       2, 0, 1, 0, 2, 2, 1, 1, 0, 0, 0, 2, 0, 0, 1, 0, 2, 2, 2, 0, 1, 1,
       2])

In [ ]:
y_test

array([2, 0, 0, 0, 2, 2, 0, 1, 0, 0, 1, 2, 1, 2, 2, 1, 0, 1, 0, 0, 1, 1,
       2, 0, 1, 0, 2, 2, 1, 1, 0, 0, 0, 2, 0, 0, 1, 0, 2, 2, 2, 0, 1, 1,
       2])

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_pred,y_test)


array([[18,  0,  0],
       [ 0, 13,  0],
       [ 0,  0, 14]])